CodeVisor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from ModPy.views import HomeView
from Profile.views import RegisterView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^register/', RegisterView.as_view(), name="register"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^u/', include('Profile.urls', namespace='profile')),
    url(r'^program/', include('Console.urls', namespace='console')),
    url(r'^developer/', include('ModPy.urls', namespace='developer-console')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('images/favicon.ico'),
        ),
        name="favicon"
    ),
]

Console/urls.py
from django.conf.urls import url, include

from .views import ProgramDeleteView, ProgramCreateView, ProgramUpdateView

from ModPy.api import ModuleResource, UserResource, ProfileResource

module_resource = ModuleResource()
user_resource = UserResource()
profile_resource = ProfileResource()

urlpatterns = [
    url(r'^delete/(?P<pk>[\w-]+)/$', ProgramDeleteView.as_view(), name="program-delete"),
    url(r'^create/$', ProgramCreateView.as_view(), name="program-create"),
    url(r'^c/(?P<pk>[0-9]+)/$', ProgramUpdateView.as_view(), name="program-update"),
    url(r'^api-mod/', include(module_resource.urls)),
    url(r'^api-user/', include(user_resource.urls)),
    url(r'^api-profile/', include(profile_resource.urls)),
]

ModPy/urls.py
from django.conf.urls import url, include

from .views import ModuleCreateView, ModuleUpdateView, ModuleDeleteView

urlpatterns = [
    url(r'^create/$', ModuleCreateView.as_view(), name="module-create"),
    url(r'^update/(?P<pk>[0-9]+)/$', ModuleUpdateView.as_view(), name="module-update"),
    url(r'^delete/(?P<pk>[0-9]+)/$', ModuleDeleteView.as_view(), name="module-update"),
]

Profile/urls.py
from django.conf.urls import url, include

from .views import ProfileDetailView, ProfileUpdateView


urlpatterns = [
    url(r'^$', ProfileDetailView.as_view(), name="detail"),
    url(r'^edit/$', ProfileUpdateView.as_view(), name="edit"),
]

Profile/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from CodeVisor.utils import unique_slug_generator

# Create your models here.

User = settings.AUTH_USER_MODEL

class Profile(models.Model):
	user 			= models.OneToOneField(User, on_delete=models.CASCADE)
	description 	= models.TextField(blank=True, null=True, default="Not provided")
	education		= models.CharField(max_length=120, blank=True, null=True, default="Not provided")
	company 		= models.CharField(max_length=120, blank=True, null=True, default="Not provided")
	activation_key 	= models.CharField(max_length=120, blank=True, null=True)
	activated 		= models.BooleanField(default=False)
	timestamp 		= models.DateTimeField(auto_now_add=True)
	updated 		= models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.user.username

	def get_programs(self):
		return self.user.programs.all()

def post_save_receiver(sender, instance, created, *args, **kwargs):
	profile, is_created = Profile.objects.get_or_create(user=instance)


post_save.connect(post_save_receiver, sender=User)

Profile/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class RegisterForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email',)

    def clean_username(self):
        username = self.cleaned_data.get("username")
        qs = User.objects.filter(username__iexact=username)
        if qs.exists():
            raise forms.ValidationError("Cannot use this username. It's already registered.")
        return username


    def clean_email(self):
        email = self.cleaned_data.get("email")
        qs = User.objects.filter(email__iexact=email)
        if qs.exists():
            raise forms.ValidationError("Cannot use this email. It's already registered.")
        return email

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            # print(user.profile)
            # user.profile.send_activation_email() # celery delay
        return user

class EditProfileForm(forms.ModelForm):
    """A form for updating user profiles. Includes all the required
    fields"""
    company = forms.CharField(label='company', max_length=120)
    education = forms.CharField(label='education', max_length=120)
    description = forms.CharField(label='description')

    class Meta:
        model = User
        fields = ('username', 'email','first_name', 'last_name')

    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(EditProfileForm, self).__init__(*args, **kwargs)


    def clean_username(self):
        username = self.cleaned_data.get("username")
        if username == self.user.username:
            pass
        else:
            qs = User.objects.filter(username__iexact=username)
            if qs.exists():
                raise forms.ValidationError("Cannot use this username. It's already registered.")
        return username


    def clean_email(self):
        email = self.cleaned_data.get("email")
        if email == self.user.email:
            pass
        else:
            qs = User.objects.filter(email__iexact=email)
            if qs.exists():
                raise forms.ValidationError("Cannot use this email. It's already registered.")
        return email

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(EditProfileForm, self).save(commit=False)
        if commit:
            user.save()
            profile = user.profile
            profile.company = self.cleaned_data.get("company")
            profile.education = self.cleaned_data.get("education")
            profile.description = self.cleaned_data.get("description")
            profile.save()
        return user

Profile/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.conf import settings

from .forms import RegisterForm, EditProfileForm

# Create your views here.

User = get_user_model()

class RegisterView(CreateView):
	template_name = "registration/register.html"
	form_class = RegisterForm
	success_url = "/"

class ProfileDetailView(LoginRequiredMixin, DetailView):
	template_name = "profile.html"

	def get_object(self):
		return self.request.user


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
	template_name = "registration/update.html"
	form_class = EditProfileForm
	success_url = "/u/"

	def get_object(self):
		return self.request.user

	def get_form_kwargs(self):
		kwargs = super(ProfileUpdateView, self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

Profile/templates/profile.html
{% extends "base.html" %}

{% block content %}

{% include "css/profile.css" %}

	<!-- Particles js for Profile -->
	<style type="text/css">
		#particles-js{
			height: 30vh;
		}
		@media all and (max-width: 320px) and (max-height: 568px){
			#particles-js{
		height: 40vh;
	}
		}
		@media all and (max-height: 320px) and (max-width: 568px){
			#particles-js{
		height: 50vh;
	}
		}
		@media all and (max-width: 414px) and (max-height: 736px) and (min-width: 321px) and (min-height: 569px){
			#particles-js{
				height: 35vh;
			}
		}
		@media all and (max-height: 414px) and (max-width: 736px) and (min-height: 321px) and (min-width: 569px){
			#particles-js{
				height: 40vh;
			}
		}
	</style>

	<div class="jumbotron jumbotron-fluid">
		<div id="particles-js"></div>
	</div>
	<div class="plank"></div>
	<div id="hero-unit" data-aos="fade-right">
		<div class="container">
			<h1 class="display-4">
				Welcome, {{ object.username }}
			</h1>
		</div>
	</div>
	<div class="container">
		<div class="margin">
		<hr>
		<h3 class="profile-details">
			Profile Details
			<button class="btn btn-raised btn-secondary btn-desktop btn-danger btn-md" onclick="gotoUrl('/u/edit/')"><i class="fas fa-user-edit"></i>&nbsp;Edit Profile</button>
		</h3>
		</div>
		<hr>
		<div class="profile-details">
			<p>Name: {{ object.first_name}} {{ object.last_name }}</p>
			<p>Education: <i class="fas fa-university"></i> {{ object.profile.education }}</p>
			<p>Company: <i class="fas fa-briefcase"></i> {{ object.profile.company }}</p>
			<p>About yourself:<br><br>
				{{ object.profile.description }}
			</p>
			<p>Email: <i class="fas fa-envelope"></i> {{object.email}}</p><br>
			<button class="btn btn-raised btn-secondary btn-phone btn-danger btn-md" onclick="gotoUrl('/u/edit/')"><i class="fas fa-user-edit"></i>&nbsp;Edit Profile</button>
		</div>
		<hr>
		<h3>
			My Repositories
			<button class="btn btn-raised btn-secondary btn-desktop btn-md btn-danger" onclick="window.location.href='{% url 'console:program-create' %}'"><i class="fas fa-plus"></i>&nbsp;New Program</button>
		</h3>
		<button class="btn btn-raised btn-secondary btn-phone btn-danger btn-md"><i class="fas fa-plus"></i>&nbsp;New Repository</button>
		<hr>
		<div class="row programs-section">
			{% if object.programs.exists %}
				{% for prog in object.programs.all %}
					<div class="col-lg-3 col-md-6 col-sm-12">
						<div class="card" style="width: 18rem;height: 13rem;margin: 5vh 0 12vh 0;">
							<div class="card-body" style="padding:3rem;">
								<h3 class="card-title">{{ prog.title }}</h3>
								<p class="card-text">{{ prog.description }}</p>
							</div>
							<form action="{% url 'console:program-delete' pk=prog.pk %}">
								{% csrf_token %}
								<center>
									<button class="btn btn-raised btn-success" type="button" onclick="gotoUrl('{% url 'console:program-update' pk=prog.pk %}')"><i class="fas fa-edit"></i>&nbsp;Edit</button>
									<input type="hidden" name="prog_id" value="{{ prog.pk }}">
									<button class="btn btn-raised btn-danger" type="submit"formmethod="POST">
										<i class="fas fa-trash-alt"></i>&nbsp;Delete
									</button>
								</center>
							</form>
						</div>
					</div>
				{% endfor %}
			{% else %}
			<center><h3><i class="fas fa-angle-left"></i><i class="fas fa-angle-right"></i>&nbsp;No programs saved</h3></center>

			<style type="text/css">
				.programs-section{
					background-color: #EEE;
					height: 450px;
					padding: 15% 37%;
					color: #777;
				}
			</style>
			{% endif %}
		</div>
		</div>
	</div>

	<script type="text/javascript">{% include "js/particles.js" %}</script>
	<script type="text/javascript">{% include "js/app.js" %}</script>


{% endblock content %}