CodeVisor/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from ModPy.views import HomeView
from Profile.views import RegisterView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^register/', RegisterView.as_view(), name="register"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^u/', include('Profile.urls', namespace='profile')),
    url(r'^program/', include('Console.urls', namespace='console')),
    url(r'^developer/', include('ModPy.urls', namespace='developer-console')),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^favicon.ico$',
        RedirectView.as_view(
            url=staticfiles_storage.url('images/favicon.ico'),
        ),
        name="favicon"
    ),
]

ModPy/urls.py
from django.conf.urls import url, include

from .views import ModuleCreateView, ModuleUpdateView, ModuleDeleteView

urlpatterns = [
    url(r'^create/$', ModuleCreateView.as_view(), name="module-create"),
    url(r'^update/(?P<pk>[0-9]+)/$', ModuleUpdateView.as_view(), name="module-update"),
    url(r'^delete/(?P<pk>[0-9]+)/$', ModuleDeleteView.as_view(), name="module-update"),
]

Profile/urls.py
from django.conf.urls import url, include

from .views import ProfileDetailView, ProfileUpdateView


urlpatterns = [
    url(r'^$', ProfileDetailView.as_view(), name="detail"),
    url(r'^edit/$', ProfileUpdateView.as_view(), name="edit"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" >

	<head>

		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Github</title>
		{% load staticfiles %}
		<link rel="shortcut icon" href="favicon.ico">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
		<link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css">
		<link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>

		{% include "css/style.css" %}

	</head>
	
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
		  <button class="cv-btn"><i class="fas fa-bars"></i></button>
		  <a class="navbar-brand" href="">GitHub</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-auto">
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'home' %}">Home</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="#">Pull Requests</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="#">Issues</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="#">Marketplace</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="#">Explore</a>
		      </li>
		  	{% if request.user.is_superuser %}
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'profile:detail' %}">My Profile</a>
		      </li>
			  <li class="nav-item dropdown">
			    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			      Start
			    </a>
			    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
			    	<a class="dropdown-item" href="{% url 'developer-console:module-create' %}">New Repository</a>
			    	<a class="dropdown-item" data-toggle="modal" data-target="#UpdateModule" style="cursor:pointer;">New Gist</a>
			    	<a class="dropdown-item" data-toggle="modal" data-target="#DeleteModule" style="cursor:pointer;">New Organisation</a>
			    	<a class="dropdown-item" data-toggle="modal" data-target="#DeleteModule" style="cursor:pointer;">New Project</a>
			    </div>
			  </li>
		  	{% elif request.user.is_authenticated %}
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'profile:detail' %}">My Profile</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
		      </li>
		  	{% else %}
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'login' %}">Login</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'register' %}">Register</a>
		      </li>
		  	{% endif %}
		    </ul>
				<form class="form-inline my-2 my-lg-0">
					<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
				</form>&nbsp;&nbsp;&nbsp;
				<button class="btn btn-outline-danger my-2 my-sm-0" type="button" onclick="window.location.href = {% url 'logout' %}">Logout</button>
			</div>

		</nav>
		<div>
			{% block content %}{% endblock content %}
		</div>
		<br>
		<div class="footer">
			<center>
				Made with <i class="fas fa-heart"></i> by Team GitHub
			</center>
		</div>

		<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
		<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js"></script>
		<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js"></script>
		<script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>

		<script>
			AOS.init({
				duration:1500,
			});
		</script>

		<script type="text/javascript">
			function gotoUrl(str)
			{
				window.location.href=str;
			}
			function updateMod()
			{
				window.location.href="/developer/update/"+ document.getElementById("UpdateModuleId").value;
			}
			function deleteMod()
			{
				window.location.href="/developer/delete/"+ document.getElementById("DeleteModuleId").value;
			}
		</script>

		<div class="modal fade" id="UpdateModule" tabindex="-1" role="dialog" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLongTitle">Update Module</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
				<label for="ModuleId">Module ID</label>
				<input type="text" class="form-control" id="UpdateModuleId" placeholder="Enter module id">      
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary btn-raised" data-dismiss="modal">Close</button>
		        <button type="button" class="btn btn-bg-indigo btn-raised" onclick="updateMod();">Update Module</button>
		      </div>
		    </div>
		  </div>
		</div>		

		<div class="modal fade" id="DeleteModule" tabindex="-1" role="dialog" aria-hidden="true">
		  <div class="modal-dialog modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLongTitle">Delete Module</h5>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <div class="modal-body">
				<label for="ModuleId">Module ID</label>
				<input type="text" class="form-control" id="DeleteModuleId" placeholder="Enter module id">      
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-secondary btn-raised" data-dismiss="modal">Close</button>
		        <button type="button" class="btn btn-bg-indigo btn-raised" onclick="deleteMod();">Delete Module</button>
		      </div>
		    </div>
		  </div>
		</div>		
	</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block content %}

	{% include "css/laptop.css" %}
	{% include "css/responsive.css" %}
	<!-- Responsive  -->
<style type="text/css">
@media all and (max-width:767px) and (min-width: 640px) and (max-height: 400px) and (min-height: 300px) {
  #particles-js{
    height: 100vh;
  }
  #hero-unit{
  	font-size: 80%;
  	top:20%;
  }
  #aboutus-content{
    border:none;
  }
}
@media all and (max-width:767px) and (min-width: 640px) and (max-height: 500px) and (min-height: 400px) {
  #particles-js{
    height: 100vh;
  }
  #hero-unit{
  	font-size: 100%;
  	top:20%;
  }
  #aboutus-content{
    border:none;
  }
}
@media all and (max-width:767px) and (min-width: 640px) and (max-height: 600px) and (min-height: 500px) {
  #particles-js{
    height: 100vh;
  }
  #hero-unit{
  	font-size: 120%;
  	top:20%;
  }
  #aboutus-content{
    border:none;
  }
}
@media all and (max-width:767px) and (min-width: 640px) and (max-height: 700px) and (min-height: 600px) {
  #particles-js{
    height: 70vh;
  }
  #aboutus-content{
    border:none;
  }
}
@media all and (max-width:767px) and (min-width: 640px) and (max-height: 1300px) and (min-height: 1000px) {
  #particles-js{
    height: 50vh;
  }
  #aboutus-content{
    border:none;
  }
}

@media all and (max-width:767px) and (min-width: 640px) and (max-height: 1400px) and (min-height: 1300px) {
  #particles-js{
    height: 40vh;
  }
  #aboutus-content{
    border: none;
  }
}
@media all and (min-width:768px) and (max-width: 850px)  and (max-height: 400px) and (min-height: 300px){
	#particles-js{
		height: 100vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 14%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 25px;
    padding: 20px 50px;
    font-size: 150%;
    overflow: hidden;
  	}
		
		#hero-unit{
			font-size: 80%;
			top:20%;
		}
}
@media all and (min-width:767px) and (max-width: 850px) and (max-height: 500px) and (min-height: 400px){
		#particles-js{
			height: 100vh;
		}
		.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 14%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 25px;
    padding: 20px 50px;
    font-size: 150%;
    overflow: hidden;
    }
    #hero-unit{
  	font-size: 100%;
  	top:20%;
  	}
}
@media all and (min-width:767px) and (max-width: 850px) and (max-height: 600px) and (min-height: 500px){
	#particles-js{
		height: 100vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 14%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 25px;
    padding: 20px 50px;
    font-size: 150%;
    overflow: hidden;
    }
    #hero-unit{
  	font-size: 120%;
  	top:20%;
  }
}

@media all and (min-width:767px)  and (max-width: 850px) and (max-height: 700px) and (min-height: 600px){
	#particles-js{
		height: 70vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 19%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 25px;
    padding: 20px 50px;
    font-size: 150%;
    overflow: hidden;
  }
}

@media all and (min-width:767px) and (max-width: 850px) and (max-height: 1000px) and (min-height: 700px){
		.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 19%;
    }
    #aboutus-content{
    text-align: justify;
    line-height: 25px;
    padding: 20px 50px;
    font-size: 150%;
    overflow: hidden;
	  }
}

@media all and (min-width:767px) and (max-width: 850px) and (max-height: 1300px) and (min-height: 1000px){
	#particles-js{
		height: 50vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 19%;
  }
  #aboutus-content{
    text-align: justify;
    line-height: 25px;
    padding: 20px 50px;
    font-size: 150%;
    overflow: hidden;
  }
}

@media all and (min-width:767px) and (max-width: 850px) and (max-height: 1400px) and (min-height: 1300px){
	#particles-js{
		height: 40vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 19%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 25px;
    padding: 20px 50px;
    font-size: 150%;
    overflow: hidden;
  }
}

@media all and (min-width:850px) and (max-width:1200px)  and (max-height: 400px) and (min-height: 300px){
	#particles-js{
		height: 100vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 12%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 30px;
    padding: 20px 50px;
    font-size: 175%;
    overflow: hidden;
  }
  #hero-unit{
  	font-size: 80%;
  	top:20%;
  }
}

@media all and (min-width:850px) and (max-width: 1200px) and (max-height: 500px) and (min-height: 400px){
	#particles-js{
		height: 100vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 12%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 30px;
    padding: 20px 50px;
    font-size: 175%;
    overflow: hidden;
    }
    #hero-unit{
  	font-size: 100%;
  	top:20%;
  }
}

@media all and (min-width:850px) and (max-width: 1200px) and (max-height: 600px) and (min-height: 500px){
		#particles-js{
		height: 100vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 12%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 30px;
    padding: 20px 50px;
    font-size: 175%;
    overflow: hidden;
    }
    #hero-unit{
  	font-size: 120%;
  	top:20%;
  }
}

@media all and (min-width:850px) and (max-width: 1200px) and (max-height: 700px) and (min-height: 600px){
	#particles-js{
		height: 72vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 16%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 30px;
    padding: 20px 50px;
    font-size: 175%;
    overflow: hidden;
  }
}

@media all and (min-width:850px) and (max-width: 1200px) and (max-height: 1000px) and (min-height: 700px){
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 16%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 30px;
    padding: 20px 50px;
    font-size: 175%;
    overflow: hidden;
  }
}

@media all and (min-width:850px) and (max-width: 1200px) and (max-height: 1300px) and (min-height: 1000px){
		#particles-js{
		height: 50vh;
	}
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 16%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 30px;
    padding: 20px 50px;
    font-size: 175%;
    overflow: hidden;
  }
}

@media all and (min-width:1200px) and (max-width: 1300px) and (max-height: 1000px) and (min-height: 700px){
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 7%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 30px;
    padding: 20px 50px;
    font-size: 175%;
    overflow: hidden;
  }
}

@media all and (min-width:1300px) and (max-width: 1400px) and (max-height: 1000px) and (min-height: 700px){
	.laptop {
  		width: 70%;
  		height:: 350px;
  		border: 10px solid black;
  		margin-left: 15%;
  		margin-top: 7%;
    }
     #aboutus-content{
    text-align: justify;
    line-height: 35px;
    padding: 20px 50px;
    font-size: 200%;
    overflow: hidden;
  }
}

</style>
	<div id="hero-unit" data-aos="fade-right">
		<div class="container">
		<h1 class="display-4">GitHub</h1>
		<p class="lead fon-res1">Build software better, together</p>
		<hr class="my-4">
		<p class="fon-res2">Learn how to use our platform for collaborative software development.</p>
		<p class="lead">
			<a class="btn btn-md btn-raised btn-danger " href="#" role="button">Learn more</a>
		</p>
		</div>
	</div>

	<div class="jumbotron jumbotron-fluid ">
		<div id="particles-js"></div>
	</div>

	<div class="row section">
		<div class="col-md-12 col-sm-12 col-xs-12 col-lg-12">
			<div class="container aboutus" data-aos="fade-right">
				<center>
					<h3><b>About GitHub</b></h3>
				</center>
				<div id="aboutus-content" style="border:none;">
					GitHub is a web-based hosting service for version control using Git. It is mostly used for computer code. It offers all of the distributed version control and source code management (SCM) functionality of Git as well as adding its own features.
					It provides access control and several collaboration features such as bug tracking, feature requests, task management, and wikis for every project.
					GitHub offers plans for enterprise, team, pro and free accounts[4] which are commonly used to host open-source software projects, As of January 2019, GitHub offers unlimited private repositories to all plans, including free accounts.
					As of June 2018, GitHub reports having over 28 million users and 57 million repositories (including 28 million public repositories), making it the largest host of source code in the world.				
				</div>
			</div>
		</div>
	</div>	

	<div class="row section" id="how-section">
		<div class="container-fluid" style="margin-bottom:20px;" data-aos="fade-up">
			<center><h3><b>HOW DOES IT WORK?</b></h3></center>
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12 col-lg-3" data-aos="fade-up">
			<div class="container">
				<center>
					<div class="card" style="width: 90%;">
					  <div class="icon"><i class="fas fa-hand-pointer fa-8x"></i></div><hr>
					  <div class="card-body">
					    <p class="card-text">Select Modules</p>
					  </div>
					</div>
				</center>
			</div>
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12 col-lg-3" data-aos="fade-up">
			<div class="container">
				<center>
					<div class="card" style="width: 90%;">
					  <div class="icon"><i class="fas fa-code fa-8x"></i></div><hr>
					  <div class="card-body">
					    <p class="card-text">Generate Code</p>
					  </div>
					</div>
				</center>
			</div>
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12 col-lg-3" data-aos="fade-up">
			<div class="container">
				<center>
					<div class="card" style="width: 90%;">
					  <div class="icon"><i class="fas fa-download fa-8x"></i></div><hr>
					  <div class="card-body">
					    <p class="card-text">Download Code</p>
					  </div>
					</div>
				</center>
			</div>
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12 col-lg-3" data-aos="fade-up">
			<div class="container">
				<center>
					<div class="card" style="width: 90%;">
					  <div class="icon"><i class="fas fa-cogs fa-8x"></i></div><hr>
					  <div class="card-body">
					    <p class="card-text">Run Code from Anywhere</p>
					  </div>
					</div>
				</center>
			</div>
		</div>
	</div>	
	
	<script type="text/javascript">{% include "js/particles.js" %}</script>

	<script type="text/javascript">{% include "js/app.js" %}</script>

{% endblock content %}